/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.domoticcenter.view;

import br.com.domoticcenter.componente.agendamento.JListAgendamentos;
import br.com.domoticcenter.componente.agendamento.jCheckBoxAgendamentoDiasDaSemana;
import br.com.domoticcenter.componente.lampada.JToggleButtonLampada;
import br.com.domoticcenter.entity.Agendamento;
import br.com.domoticcenter.entity.Ambiente;
import br.com.domoticcenter.entity.Lampada;
import br.com.domoticcenter.restservice.util.ResidenciaCompletaMemory;
import br.com.domoticcenter.servicedao.AgendamentoServiceDAO;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;

/**
 *
 * @author mauricio.mazzocco
 */
public class PanelAgendamento extends javax.swing.JPanel {

    private JList listAgendamentos;
    private Timer threadLampadas;
    private Ambiente ambienteSelecionado;
    private Lampada lampadaeSelecionada;
    private int indiceAmbienteNaLista = 0;
    private List<JToggleButtonLampada> toggleButtonList;
    private List<Lampada> lampadasComIDSelecionado;
    private Agendamento agendamento;

    public List<Lampada> getLampadasComIDSelecionado() {
        return lampadasComIDSelecionado;
    }
    private final String iconPatch = "/br/com/domoticcenter/imagens/";
    private boolean executarThreadLamapdas = false;

    public JPanel getjPanel1() {
        return jPanel1;
    }
  public JPanel getjPanel2() {
        return jPanel2;
    }

    private boolean estaCarregando;

    public boolean isEstaCarregando() {
        return estaCarregando;
    }

    public void setEstaCarregando(boolean estaCarregando) {
        this.estaCarregando = estaCarregando;
    }
   
    private ImageIcon loader = new ImageIcon(getClass().getResource(iconPatch + "carregando.gif"));
   
    public ArrayList<JLabel> getProgressToggleButton() {
        return progressToggleButton;
    }

    public void setProgressToggleButton(ArrayList<JLabel> progressToggleButton) {
        this.progressToggleButton = progressToggleButton;
    }
    private ArrayList<JLabel> progressToggleButton = new ArrayList();
 
  

    /**
     * Creates new form PanelTeste
     */
    public PanelAgendamento() {
        initComponents();
       
    }

    public PanelAgendamento(String login, String senha) {
        initComponents();
        final Icon tabLine = new ImageIcon(getClass().getResource(iconPatch + "tab_line.png"));
        JLabel jLabeLine = new JLabel(tabLine);
        jLabeLine.setBounds(0, 0, 610, 10);
        jPanel3.add(jLabeLine);
     
        final Icon listLine = new ImageIcon(getClass().getResource(iconPatch + "line.png"));
        JLabel jLabeListLine = new JLabel(listLine);
        jLabeListLine.setBounds(0, 0, 8, 360);
        jPanel4.add(jLabeListLine);
        jPanel2.setVisible(false);
        carregaAgendamento();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAcao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nomeAgendamento = new javax.swing.JTextField();
        jSpinnerHora = new javax.swing.JSpinner();
        jSpinnerMinutos = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new jCheckBoxAgendamentoDiasDaSemana("1");
        jLabel4 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(300, 350));
        setRequestFocusEnabled(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(160, 150));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jSpinnerHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jSpinnerMinutos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hora : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome :");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Minuto:");

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Segunda");
        jCheckBox1.setActionCommand("1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dias da Semana:");

        jCheckBox2.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Terça");
        jCheckBox2.setActionCommand("2");

        jCheckBox3.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Quarta");
        jCheckBox3.setActionCommand("3");

        jCheckBox4.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Quinta");
        jCheckBox4.setActionCommand("4");

        jCheckBox5.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Sexta");
        jCheckBox5.setActionCommand("5");

        jCheckBox6.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("Sabado");
        jCheckBox6.setActionCommand("6");

        jCheckBox7.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setText("Domingo");
        jCheckBox7.setActionCommand("7");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ação : ");

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupAcao.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setActionCommand("des");
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Desligar");

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupAcao.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setActionCommand("lig");
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Ligar");

        jButton1.setText("Salvar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeAgendamento))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(90, 90, 90))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
      if(diasDaSemanaSelecionado() != null){  
        if(buttonGroupAcao.getSelection().getActionCommand().equalsIgnoreCase("lig")){
            agendamento.setEstadoObjeto(true);
        }else{
             agendamento.setEstadoObjeto(false);
        }
      
        agendamento.setHora((Integer)jSpinnerHora.getValue());
        agendamento.setMinuto((Integer)jSpinnerMinutos.getValue());
        agendamento.setDiasNaSemana(diasDaSemanaSelecionado());
      
      }
   
      boolean foiCadastradoComSucesso = AgendamentoServiceDAO.cadastraAgendamento(agendamento);
      if(foiCadastradoComSucesso){
          
          ResidenciaCompletaMemory.getResidenciaCompleta().setAgendamentos(AgendamentoServiceDAO.listaTodosAgendamentosPorIPDomotic(ResidenciaCompletaMemory.getIpDomoticCenter()));
          carregaAgendamento();
          listAgendamentos.setSelectedIndex((listAgendamentos.getModel().getSize()-1));
        
      }
       
       
        System.out.println("Agendamento completo " 
                +" Nome : " + agendamento.getNome() 
                +" IpdomoticCenter " + agendamento.getIpDomoticCenter()
                +" Dias Da semana " + agendamento.getDiasNaSemana()
                +" IDAmbiente " + agendamento.getAmbienteID()
                +" Posicao Ambiente  " + agendamento.getPosicaoAmbiente()
                +" Posicao Item " + agendamento.getPosicaoObjAmbiente()
                +" Tipo de objeto " + agendamento.getTipoObjeto()
                +" HORA " + agendamento.getHora()
                +" MINUTO " + agendamento.getMinuto()
                +" Esta Ativo " + agendamento.isAtivo()
                +" Ligado ou DesliLigadogado " + agendamento.isEstadoObjeto()
            
                );
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    public void carregaAgendamento() {

        jPanel1.removeAll();
        jPanel1.setLayout(new GridLayout(1, 0));        
        listAgendamentos = new JListAgendamentos(this);
        jPanel1.add(listAgendamentos);
        jPanel1.setVisible(false);
        jPanel1.setVisible(true);
        
   
    }
public void carregaConfiguracaoAgendamento(Object objeto, int posicaoAmbiente, int posicItem) {
    
   
   jPanel2.setVisible(true);
   alteraComponentesParaDefault();
   agendamento =  new Agendamento();
   

    
    if(objeto instanceof Lampada){
        Lampada lampada =(Lampada)objeto;
        nomeAgendamento.setText(lampada.getNome());
        agendamento.setNome(lampada.getNome());
        agendamento.setTipoObjeto(0);
        agendamento.setAmbienteID(lampada.getAmbienteID());
         
    }
    agendamento.setPosicaoAmbiente(posicaoAmbiente);
    agendamento.setAtivo(true);
    agendamento.setPosicaoObjAmbiente(posicItem);
    agendamento.setIpDomoticCenter(ResidenciaCompletaMemory.getIpDomoticCenter());
        
    
    
    
}
    public void carregaConfiguracaoAgendamento(Agendamento agendamento) {
        
         jPanel2.setVisible(true);
         //alteraComponentesParaDefault();
         marcaCheckBoxDiasDaSemana(agendamento.getDiasNaSemana());
         if(agendamento.isEstadoObjeto()){
             buttonGroupAcao.setSelected(jRadioButton2.getModel(), true);
         }else{
              buttonGroupAcao.setSelected(jRadioButton1.getModel(), true);
         }
         nomeAgendamento.setText(agendamento.getNome());
         jSpinnerHora.setValue((Integer)agendamento.getHora() );
         jSpinnerMinutos.setValue((Integer)agendamento.getMinuto());
    

    }
    
    private String diasDaSemanaSelecionado(){
        String diasSelecionados="";
        boolean selecionouCheckbox = false;
        if(jCheckBox1.isSelected()){
            diasSelecionados +=jCheckBox1.getActionCommand()+",";
            selecionouCheckbox= true;
        }
        if(jCheckBox2.isSelected()){
               diasSelecionados +=jCheckBox2.getActionCommand()+",";
               selecionouCheckbox= true;
          }
        if(jCheckBox3.isSelected()){
               diasSelecionados +=jCheckBox3.getActionCommand()+",";
               selecionouCheckbox= true;
          }
        if(jCheckBox4.isSelected()){
               diasSelecionados +=jCheckBox4.getActionCommand()+",";
               selecionouCheckbox= true;
          }
        if(jCheckBox5.isSelected()){
               diasSelecionados +=jCheckBox5.getActionCommand()+",";
               selecionouCheckbox= true;
          }
        if(jCheckBox6.isSelected()){
               diasSelecionados+=jCheckBox6.getActionCommand()+",";
               selecionouCheckbox= true;
          }
        if(jCheckBox7.isSelected()){
               diasSelecionados +=jCheckBox7.getActionCommand()+ " ";
               selecionouCheckbox = true;
          }
         
            if (selecionouCheckbox)
             return diasSelecionados.substring(0,diasSelecionados.length() -1 );
            
            return null;
    }

    private void alteraComponentesParaDefault(){
        
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
              
        buttonGroupAcao.setSelected(jRadioButton2.getModel(), true);
        carregaAgendamento();
        
        jSpinnerHora.setValue(0);
        jSpinnerMinutos.setValue(0);
        
    }
    
    
    public void marcaCheckBoxDiasDaSemana(String diasSelecionados){
        String[] diaSelecionado =  diasSelecionados.split(",");   
        for (int i=0; i<diaSelecionado.length; i++){
            switch(diaSelecionado[i]){
               case "1" :   jCheckBox1.setSelected(true);
                             break;
               case "2" :   jCheckBox2.setSelected(true);
                             break;
               case "3" :   jCheckBox3.setSelected(true);
                             break;
               case "4" :   jCheckBox4.setSelected(true);
                             break;
               case "5" :   jCheckBox5.setSelected(true);
                             break;
               case "6" :   jCheckBox6.setSelected(true);
                             break;
               case "7" :   jCheckBox7.setSelected(true);
                             break;
            }
        }
            
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAcao;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner jSpinnerHora;
    private javax.swing.JSpinner jSpinnerMinutos;
    private javax.swing.JTextField nomeAgendamento;
    // End of variables declaration//GEN-END:variables
}
